### ISSUE TITLE
OAuthexception

### ISSUE THREAD

**Issue by zenmodelol** [natanlao/reddit-transfer#4]
Hi, sorry for the newbie question. 

Currently while following the usage steps I receive  

   raise OAuthException(
prawcore.exceptions.OAuthException: invalid_grant error processing request

My accounts dosen't have MFA and I did not key it into the script. I have also double checked my password and username credentials. Could you help me please?

**Comment by natanlao** [comment]
Hi! Not a newbie question at all. In my experience, this error indicates that there's an authentication issue. I would check the credentials you provided to `python reddit_transfer.py login $USERNAME` -- did you follow this process?

1. Log in to $OLD_REDDIT_ACCOUNT
2. Authorize a `script` app under $OLD_REDDIT_ACCOUNT
3. Provide the $OLD_REDDIT_ACCOUNT `script` keys to `python reddit_transfer.py login $OLD_USERNAME`
4. Log in to $NEW_REDDIT_ACCOUNT
5. Authorized a `script` app under $NEW_REDDIT_ACCOUNT
6. Provide the $NEW_REDDIT_ACCOUNT `script` keys to `python reddit_transfer.py login $NEW_USERNAME`

If you want to verify which keys reddit-transfer is using, look for a file named praw.ini in the reddit-transfer directory.

**Comment by zenmodelol** [comment]
Hi, I think it works now! My mistake was in the authorization. I had made a false presumption that I only had to allow the personal use script on one side. Thank you so much for your help, I appreciate it!

**Comment by natanlao** [comment]
That's good to hear! I'm going to reopen this ticket; upon inspection, this isn't properly documented, and ideally, the script should warn if it sees that two accounts are using the same keys.
